name: City Listings
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6883632291574031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f4d50'
    - '#202020'
    - '#71838d'
    - '#fefdee'
    - '#845944'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
