name: City Listings
favicon: null
layout_spectrum: 0.7059644246473908
typography_spectrum: 0.6883632291574031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2257229876704514
  lightness: 0.7047657559160143
  saturation: 0.8432558770291507
  rhythmicContrast: 0.9275661415886134
purpose: []
